### ISSUE TITLE
Construct notes playground for implement

### ISSUE THREAD

**Issue by HyunmoAhn** [HyunmoAhn/notes#13]
## Purpose
- Can implement code level for each issues.
- Visitor can know easyly to performing issues.

## Todo 
- [ ] Set config of [storybook](https://storybook.js.org/)
- [ ] make design template to visualization
- [ ] deploy homepage on public url
